### ISSUE TITLE
Unknown error while logging in to TTLOCK

### ISSUE THREAD

**Issue by x-iLex-x** [jbergler/hass-ttlock#74]
My locks stopped working instantly today morning.

I’ve tried to remove integration, reset my client id on open.ttlock and then set up integration again, but saw “unknown error occurred” while trying to log in with my TTlock account. 

TTLock native app continue working perfectly. I suggest, that it is not ttlock cloud problem.

I see this error in log:

`Logger: homeassistant.config_entries
Source: config_entries.py:399
First occurred: 11:39:50 (2 occurrences)
Last logged: 11:43:20

Error setting up entry TTLock for ttlock
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 399, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ttlock/__init__.py", line 70, in async_setup_entry
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 255, in async_config_entry_first_refresh
    await self._async_refresh(
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ttlock/coordinator.py", line 140, in _async_update_data
    state = await self.api.get_lock_state(self.lock_id)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ttlock/api.py", line 154, in get_lock_state
    async with GW_LOCK:
  File "/usr/local/lib/python3.11/asyncio/locks.py", line 15, in __aenter__
    await self.acquire()
  File "/usr/local/lib/python3.11/asyncio/locks.py", line 114, in acquire
    await fut
asyncio.exceptions.CancelledError: aiohttp connection lost
`

I’m running 100% stable and fast internet connection, I have no idea how did it happen.

**Comment by jbergler** [comment]
Is this issue still happening? I'm going to close the issue for the time being but if the problem returns please let me know.
